// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: registry.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FullyQualifiedName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullyQualifiedName) Reset() {
	*x = FullyQualifiedName{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullyQualifiedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullyQualifiedName) ProtoMessage() {}

func (x *FullyQualifiedName) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullyQualifiedName.ProtoReflect.Descriptor instead.
func (*FullyQualifiedName) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *FullyQualifiedName) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FullyQualifiedName) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FullyQualifiedName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtifactIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Fqn   *FullyQualifiedName    `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*ArtifactIdentifier_VersionHash
	//	*ArtifactIdentifier_Tag
	Identifier    isArtifactIdentifier_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactIdentifier) Reset() {
	*x = ArtifactIdentifier{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactIdentifier) ProtoMessage() {}

func (x *ArtifactIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactIdentifier.ProtoReflect.Descriptor instead.
func (*ArtifactIdentifier) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactIdentifier) GetFqn() *FullyQualifiedName {
	if x != nil {
		return x.Fqn
	}
	return nil
}

func (x *ArtifactIdentifier) GetIdentifier() isArtifactIdentifier_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ArtifactIdentifier) GetVersionHash() string {
	if x != nil {
		if x, ok := x.Identifier.(*ArtifactIdentifier_VersionHash); ok {
			return x.VersionHash
		}
	}
	return ""
}

func (x *ArtifactIdentifier) GetTag() string {
	if x != nil {
		if x, ok := x.Identifier.(*ArtifactIdentifier_Tag); ok {
			return x.Tag
		}
	}
	return ""
}

type isArtifactIdentifier_Identifier interface {
	isArtifactIdentifier_Identifier()
}

type ArtifactIdentifier_VersionHash struct {
	VersionHash string `protobuf:"bytes,2,opt,name=versionHash,proto3,oneof"`
}

type ArtifactIdentifier_Tag struct {
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3,oneof"`
}

func (*ArtifactIdentifier_VersionHash) isArtifactIdentifier_Identifier() {}

func (*ArtifactIdentifier_Tag) isArtifactIdentifier_Identifier() {}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqn           *FullyQualifiedName    `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	VersionHash   string                 `protobuf:"bytes,2,opt,name=versionHash,proto3" json:"versionHash,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *MetaData              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Artifact) GetFqn() *FullyQualifiedName {
	if x != nil {
		return x.Fqn
	}
	return nil
}

func (x *Artifact) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *Artifact) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Artifact) GetMetadata() *MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Pulls         int64                  `protobuf:"varint,2,opt,name=pulls,proto3" json:"pulls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *MetaData) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *MetaData) GetPulls() int64 {
	if x != nil {
		return x.Pulls
	}
	return 0
}

type ArtifactQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *string                `protobuf:"bytes,1,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Author        *string                `protobuf:"bytes,2,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactQuery) Reset() {
	*x = ArtifactQuery{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactQuery) ProtoMessage() {}

func (x *ArtifactQuery) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactQuery.ProtoReflect.Descriptor instead.
func (*ArtifactQuery) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ArtifactQuery) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ArtifactQuery) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *ArtifactQuery) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ArtifactListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*Artifact            `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactListResponse) Reset() {
	*x = ArtifactListResponse{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactListResponse) ProtoMessage() {}

func (x *ArtifactListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactListResponse.ProtoReflect.Descriptor instead.
func (*ArtifactListResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactListResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactContent) Reset() {
	*x = ArtifactContent{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactContent) ProtoMessage() {}

func (x *ArtifactContent) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactContent.ProtoReflect.Descriptor instead.
func (*ArtifactContent) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*UploadArtifactRequest_Metadata
	//	*UploadArtifactRequest_Content
	Request       isUploadArtifactRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactRequest) Reset() {
	*x = UploadArtifactRequest{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactRequest) ProtoMessage() {}

func (x *UploadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactRequest.ProtoReflect.Descriptor instead.
func (*UploadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *UploadArtifactRequest) GetRequest() isUploadArtifactRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UploadArtifactRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Request.(*UploadArtifactRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadArtifactRequest) GetContent() *ArtifactContent {
	if x != nil {
		if x, ok := x.Request.(*UploadArtifactRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isUploadArtifactRequest_Request interface {
	isUploadArtifactRequest_Request()
}

type UploadArtifactRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadArtifactRequest_Content struct {
	Content *ArtifactContent `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*UploadArtifactRequest_Metadata) isUploadArtifactRequest_Request() {}

func (*UploadArtifactRequest_Content) isUploadArtifactRequest_Request() {}

type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqn           *FullyQualifiedName    `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

func (x *UploadMetadata) GetFqn() *FullyQualifiedName {
	if x != nil {
		return x.Fqn
	}
	return nil
}

func (x *UploadMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddRemoveTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqn           *FullyQualifiedName    `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	VersionHash   string                 `protobuf:"bytes,2,opt,name=versionHash,proto3" json:"versionHash,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRemoveTagRequest) Reset() {
	*x = AddRemoveTagRequest{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRemoveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemoveTagRequest) ProtoMessage() {}

func (x *AddRemoveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemoveTagRequest.ProtoReflect.Descriptor instead.
func (*AddRemoveTagRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

func (x *AddRemoveTagRequest) GetFqn() *FullyQualifiedName {
	if x != nil {
		return x.Fqn
	}
	return nil
}

func (x *AddRemoveTagRequest) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *AddRemoveTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\bregistry\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\x12FullyQualifiedName\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x12ArtifactIdentifier\x12.\n" +
	"\x03fqn\x18\x01 \x01(\v2\x1c.registry.FullyQualifiedNameR\x03fqn\x12\"\n" +
	"\vversionHash\x18\x02 \x01(\tH\x00R\vversionHash\x12\x12\n" +
	"\x03tag\x18\x03 \x01(\tH\x00R\x03tagB\f\n" +
	"\n" +
	"identifier\"\xa0\x01\n" +
	"\bArtifact\x12.\n" +
	"\x03fqn\x18\x01 \x01(\v2\x1c.registry.FullyQualifiedNameR\x03fqn\x12 \n" +
	"\vversionHash\x18\x02 \x01(\tR\vversionHash\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12.\n" +
	"\bmetadata\x18\x04 \x01(\v2\x12.registry.MetaDataR\bmetadata\"V\n" +
	"\bMetaData\x124\n" +
	"\acreated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x14\n" +
	"\x05pulls\x18\x02 \x01(\x03R\x05pulls\"\x81\x01\n" +
	"\rArtifactQuery\x12\x1b\n" +
	"\x06source\x18\x01 \x01(\tH\x00R\x06source\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x02 \x01(\tH\x01R\x06author\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\t\n" +
	"\a_sourceB\t\n" +
	"\a_authorB\a\n" +
	"\x05_name\"H\n" +
	"\x14ArtifactListResponse\x120\n" +
	"\tartifacts\x18\x01 \x03(\v2\x12.registry.ArtifactR\tartifacts\"%\n" +
	"\x0fArtifactContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x91\x01\n" +
	"\x15UploadArtifactRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.registry.UploadMetadataH\x00R\bmetadata\x125\n" +
	"\acontent\x18\x02 \x01(\v2\x19.registry.ArtifactContentH\x00R\acontentB\t\n" +
	"\arequest\"T\n" +
	"\x0eUploadMetadata\x12.\n" +
	"\x03fqn\x18\x01 \x01(\v2\x1c.registry.FullyQualifiedNameR\x03fqn\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"y\n" +
	"\x13AddRemoveTagRequest\x12.\n" +
	"\x03fqn\x18\x01 \x01(\v2\x1c.registry.FullyQualifiedNameR\x03fqn\x12 \n" +
	"\vversionHash\x18\x02 \x01(\tR\vversionHash\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag2\xf2\x03\n" +
	"\x0fRegistryService\x12I\n" +
	"\x0eQueryArtifacts\x12\x17.registry.ArtifactQuery\x1a\x1e.registry.ArtifactListResponse\x12I\n" +
	"\fPullArtifact\x12\x1c.registry.ArtifactIdentifier\x1a\x19.registry.ArtifactContent0\x01\x12G\n" +
	"\x0eUploadArtifact\x12\x1f.registry.UploadArtifactRequest\x1a\x12.registry.Artifact(\x01\x12B\n" +
	"\x0eDeleteArtifact\x12\x1c.registry.ArtifactIdentifier\x1a\x12.registry.Artifact\x12?\n" +
	"\vGetArtifact\x12\x1c.registry.ArtifactIdentifier\x1a\x12.registry.Artifact\x12;\n" +
	"\x06AddTag\x12\x1d.registry.AddRemoveTagRequest\x1a\x12.registry.Artifact\x12>\n" +
	"\tRemoveTag\x12\x1d.registry.AddRemoveTagRequest\x1a\x12.registry.ArtifactB\fZ\n" +
	"proto_gen/b\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_registry_proto_goTypes = []any{
	(*FullyQualifiedName)(nil),    // 0: registry.FullyQualifiedName
	(*ArtifactIdentifier)(nil),    // 1: registry.ArtifactIdentifier
	(*Artifact)(nil),              // 2: registry.Artifact
	(*MetaData)(nil),              // 3: registry.MetaData
	(*ArtifactQuery)(nil),         // 4: registry.ArtifactQuery
	(*ArtifactListResponse)(nil),  // 5: registry.ArtifactListResponse
	(*ArtifactContent)(nil),       // 6: registry.ArtifactContent
	(*UploadArtifactRequest)(nil), // 7: registry.UploadArtifactRequest
	(*UploadMetadata)(nil),        // 8: registry.UploadMetadata
	(*AddRemoveTagRequest)(nil),   // 9: registry.AddRemoveTagRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_registry_proto_depIdxs = []int32{
	0,  // 0: registry.ArtifactIdentifier.fqn:type_name -> registry.FullyQualifiedName
	0,  // 1: registry.Artifact.fqn:type_name -> registry.FullyQualifiedName
	3,  // 2: registry.Artifact.metadata:type_name -> registry.MetaData
	10, // 3: registry.MetaData.created:type_name -> google.protobuf.Timestamp
	2,  // 4: registry.ArtifactListResponse.artifacts:type_name -> registry.Artifact
	8,  // 5: registry.UploadArtifactRequest.metadata:type_name -> registry.UploadMetadata
	6,  // 6: registry.UploadArtifactRequest.content:type_name -> registry.ArtifactContent
	0,  // 7: registry.UploadMetadata.fqn:type_name -> registry.FullyQualifiedName
	0,  // 8: registry.AddRemoveTagRequest.fqn:type_name -> registry.FullyQualifiedName
	4,  // 9: registry.RegistryService.QueryArtifacts:input_type -> registry.ArtifactQuery
	1,  // 10: registry.RegistryService.PullArtifact:input_type -> registry.ArtifactIdentifier
	7,  // 11: registry.RegistryService.UploadArtifact:input_type -> registry.UploadArtifactRequest
	1,  // 12: registry.RegistryService.DeleteArtifact:input_type -> registry.ArtifactIdentifier
	1,  // 13: registry.RegistryService.GetArtifact:input_type -> registry.ArtifactIdentifier
	9,  // 14: registry.RegistryService.AddTag:input_type -> registry.AddRemoveTagRequest
	9,  // 15: registry.RegistryService.RemoveTag:input_type -> registry.AddRemoveTagRequest
	5,  // 16: registry.RegistryService.QueryArtifacts:output_type -> registry.ArtifactListResponse
	6,  // 17: registry.RegistryService.PullArtifact:output_type -> registry.ArtifactContent
	2,  // 18: registry.RegistryService.UploadArtifact:output_type -> registry.Artifact
	2,  // 19: registry.RegistryService.DeleteArtifact:output_type -> registry.Artifact
	2,  // 20: registry.RegistryService.GetArtifact:output_type -> registry.Artifact
	2,  // 21: registry.RegistryService.AddTag:output_type -> registry.Artifact
	2,  // 22: registry.RegistryService.RemoveTag:output_type -> registry.Artifact
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	file_registry_proto_msgTypes[1].OneofWrappers = []any{
		(*ArtifactIdentifier_VersionHash)(nil),
		(*ArtifactIdentifier_Tag)(nil),
	}
	file_registry_proto_msgTypes[4].OneofWrappers = []any{}
	file_registry_proto_msgTypes[7].OneofWrappers = []any{
		(*UploadArtifactRequest_Metadata)(nil),
		(*UploadArtifactRequest_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
