// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.5
// source: registry.proto

package proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_QueryArtifacts_FullMethodName = "/registry.RegistryService/QueryArtifacts"
	RegistryService_PullArtifact_FullMethodName   = "/registry.RegistryService/PullArtifact"
	RegistryService_UploadArtifact_FullMethodName = "/registry.RegistryService/UploadArtifact"
	RegistryService_DeleteArtifact_FullMethodName = "/registry.RegistryService/DeleteArtifact"
	RegistryService_GetArtifact_FullMethodName    = "/registry.RegistryService/GetArtifact"
	RegistryService_AddTag_FullMethodName         = "/registry.RegistryService/AddTag"
	RegistryService_RemoveTag_FullMethodName      = "/registry.RegistryService/RemoveTag"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryServiceClient interface {
	QueryArtifacts(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*ArtifactListResponse, error)
	PullArtifact(ctx context.Context, in *ArtifactIdentifier, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactContent], error)
	UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadArtifactRequest, Artifact], error)
	DeleteArtifact(ctx context.Context, in *ArtifactIdentifier, opts ...grpc.CallOption) (*Artifact, error)
	GetArtifact(ctx context.Context, in *ArtifactIdentifier, opts ...grpc.CallOption) (*Artifact, error)
	AddTag(ctx context.Context, in *AddRemoveTagRequest, opts ...grpc.CallOption) (*Artifact, error)
	RemoveTag(ctx context.Context, in *AddRemoveTagRequest, opts ...grpc.CallOption) (*Artifact, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) QueryArtifacts(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*ArtifactListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactListResponse)
	err := c.cc.Invoke(ctx, RegistryService_QueryArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) PullArtifact(ctx context.Context, in *ArtifactIdentifier, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactContent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RegistryService_ServiceDesc.Streams[0], RegistryService_PullArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArtifactIdentifier, ArtifactContent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegistryService_PullArtifactClient = grpc.ServerStreamingClient[ArtifactContent]

func (c *registryServiceClient) UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadArtifactRequest, Artifact], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RegistryService_ServiceDesc.Streams[1], RegistryService_UploadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadArtifactRequest, Artifact]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegistryService_UploadArtifactClient = grpc.ClientStreamingClient[UploadArtifactRequest, Artifact]

func (c *registryServiceClient) DeleteArtifact(ctx context.Context, in *ArtifactIdentifier, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, RegistryService_DeleteArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetArtifact(ctx context.Context, in *ArtifactIdentifier, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, RegistryService_GetArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) AddTag(ctx context.Context, in *AddRemoveTagRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, RegistryService_AddTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) RemoveTag(ctx context.Context, in *AddRemoveTagRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, RegistryService_RemoveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
type RegistryServiceServer interface {
	QueryArtifacts(context.Context, *ArtifactQuery) (*ArtifactListResponse, error)
	PullArtifact(*ArtifactIdentifier, grpc.ServerStreamingServer[ArtifactContent]) error
	UploadArtifact(grpc.ClientStreamingServer[UploadArtifactRequest, Artifact]) error
	DeleteArtifact(context.Context, *ArtifactIdentifier) (*Artifact, error)
	GetArtifact(context.Context, *ArtifactIdentifier) (*Artifact, error)
	AddTag(context.Context, *AddRemoveTagRequest) (*Artifact, error)
	RemoveTag(context.Context, *AddRemoveTagRequest) (*Artifact, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) QueryArtifacts(context.Context, *ArtifactQuery) (*ArtifactListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryArtifacts not implemented")
}
func (UnimplementedRegistryServiceServer) PullArtifact(*ArtifactIdentifier, grpc.ServerStreamingServer[ArtifactContent]) error {
	return status.Errorf(codes.Unimplemented, "method PullArtifact not implemented")
}
func (UnimplementedRegistryServiceServer) UploadArtifact(grpc.ClientStreamingServer[UploadArtifactRequest, Artifact]) error {
	return status.Errorf(codes.Unimplemented, "method UploadArtifact not implemented")
}
func (UnimplementedRegistryServiceServer) DeleteArtifact(context.Context, *ArtifactIdentifier) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArtifact not implemented")
}
func (UnimplementedRegistryServiceServer) GetArtifact(context.Context, *ArtifactIdentifier) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtifact not implemented")
}
func (UnimplementedRegistryServiceServer) AddTag(context.Context, *AddRemoveTagRequest) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTag not implemented")
}
func (UnimplementedRegistryServiceServer) RemoveTag(context.Context, *AddRemoveTagRequest) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTag not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_QueryArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).QueryArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_QueryArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).QueryArtifacts(ctx, req.(*ArtifactQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_PullArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ArtifactIdentifier)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServiceServer).PullArtifact(m, &grpc.GenericServerStream[ArtifactIdentifier, ArtifactContent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegistryService_PullArtifactServer = grpc.ServerStreamingServer[ArtifactContent]

func _RegistryService_UploadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RegistryServiceServer).UploadArtifact(&grpc.GenericServerStream[UploadArtifactRequest, Artifact]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegistryService_UploadArtifactServer = grpc.ClientStreamingServer[UploadArtifactRequest, Artifact]

func _RegistryService_DeleteArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).DeleteArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_DeleteArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).DeleteArtifact(ctx, req.(*ArtifactIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetArtifact(ctx, req.(*ArtifactIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_AddTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).AddTag(ctx, req.(*AddRemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_RemoveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).RemoveTag(ctx, req.(*AddRemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryArtifacts",
			Handler:    _RegistryService_QueryArtifacts_Handler,
		},
		{
			MethodName: "DeleteArtifact",
			Handler:    _RegistryService_DeleteArtifact_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _RegistryService_GetArtifact_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _RegistryService_AddTag_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _RegistryService_RemoveTag_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullArtifact",
			Handler:       _RegistryService_PullArtifact_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadArtifact",
			Handler:       _RegistryService_UploadArtifact_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "registry.proto",
}
